/**
 * Large bilingual word bank for Word Royale.
 * Each entry: word, phonetic, meaning_zh, meaning_en, pos, difficulty (1-3), theme
 */
module.exports = [
  // —— daily / core ——
  { word: 'about', phonetic: '/əˈbaʊt/', meaning_zh: '关于；大约', meaning_en: 'concerning; approximately', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'accept', phonetic: '/əkˈsept/', meaning_zh: '接受', meaning_en: 'to agree to take or receive', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'across', phonetic: '/əˈkrɒs/', meaning_zh: '穿过；在对面', meaning_en: 'from one side to the other', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'action', phonetic: '/ˈækʃn/', meaning_zh: '行动；动作', meaning_en: 'the process of doing something', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'active', phonetic: '/ˈæktɪv/', meaning_zh: '积极的；活跃的', meaning_en: 'doing a lot; energetic', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'actually', phonetic: '/ˈæktʃuəli/', meaning_zh: '实际上', meaning_en: 'in fact; really', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'add', phonetic: '/æd/', meaning_zh: '添加；增加', meaning_en: 'to put something with another', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'address', phonetic: '/əˈdres/', meaning_zh: '地址；演讲', meaning_en: 'where someone lives; a speech', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'adult', phonetic: '/ˈædʌlt/', meaning_zh: '成年人', meaning_en: 'a fully grown person', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'advice', phonetic: '/ədˈvaɪs/', meaning_zh: '建议', meaning_en: 'an opinion about what to do', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'afford', phonetic: '/əˈfɔːd/', meaning_zh: '负担得起', meaning_en: 'to have enough money for', pos: 'v', difficulty: 2, theme: 'daily' },
  { word: 'afraid', phonetic: '/əˈfreɪd/', meaning_zh: '害怕的', meaning_en: 'feeling fear', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'after', phonetic: '/ˈɑːftə(r)/', meaning_zh: '在…之后', meaning_en: 'later than', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'again', phonetic: '/əˈɡen/', meaning_zh: '再次', meaning_en: 'one more time', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'against', phonetic: '/əˈɡenst/', meaning_zh: '反对；靠着', meaning_en: 'in opposition to', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'age', phonetic: '/eɪdʒ/', meaning_zh: '年龄；时代', meaning_en: 'how old someone is', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'agree', phonetic: '/əˈɡriː/', meaning_zh: '同意', meaning_en: 'to have the same opinion', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'ahead', phonetic: '/əˈhed/', meaning_zh: '在前面', meaning_en: 'in front; further on', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'air', phonetic: '/eə(r)/', meaning_zh: '空气', meaning_en: 'the mixture of gases we breathe', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'almost', phonetic: '/ˈɔːlməʊst/', meaning_zh: '几乎', meaning_en: 'nearly; not quite', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'alone', phonetic: '/əˈləʊn/', meaning_zh: '独自的', meaning_en: 'without other people', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'along', phonetic: '/əˈlɒŋ/', meaning_zh: '沿着', meaning_en: 'from one end to the other of', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'already', phonetic: '/ɔːlˈredi/', meaning_zh: '已经', meaning_en: 'before now', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'also', phonetic: '/ˈɔːlsəʊ/', meaning_zh: '也', meaning_en: 'in addition; too', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'always', phonetic: '/ˈɔːlweɪz/', meaning_zh: '总是', meaning_en: 'at all times', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'among', phonetic: '/əˈmʌŋ/', meaning_zh: '在…之中', meaning_en: 'in the middle of', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', meaning_zh: '数量', meaning_en: 'a quantity of something', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'angry', phonetic: '/ˈæŋɡri/', meaning_zh: '生气的', meaning_en: 'feeling strong dislike or rage', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'animal', phonetic: '/ˈænɪml/', meaning_zh: '动物', meaning_en: 'a living creature that is not a plant', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'another', phonetic: '/əˈnʌðə(r)/', meaning_zh: '另一个', meaning_en: 'one more; a different one', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'answer', phonetic: '/ˈɑːnsə(r)/', meaning_zh: '回答；答案', meaning_en: 'a reply; a solution', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'anyone', phonetic: '/ˈeniwʌn/', meaning_zh: '任何人', meaning_en: 'any person', pos: 'pron', difficulty: 1, theme: 'daily' },
  { word: 'appear', phonetic: '/əˈpɪə(r)/', meaning_zh: '出现；似乎', meaning_en: 'to become visible; to seem', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'area', phonetic: '/ˈeəriə/', meaning_zh: '区域；面积', meaning_en: 'a part of a place', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'arm', phonetic: '/ɑːm/', meaning_zh: '手臂', meaning_en: 'the part of the body from shoulder to hand', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'around', phonetic: '/əˈraʊnd/', meaning_zh: '周围；大约', meaning_en: 'on every side; approximately', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'arrive', phonetic: '/əˈraɪv/', meaning_zh: '到达', meaning_en: 'to reach a place', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'art', phonetic: '/ɑːt/', meaning_zh: '艺术', meaning_en: 'creative work like painting or music', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'article', phonetic: '/ˈɑːtɪkl/', meaning_zh: '文章；物品', meaning_en: 'a piece of writing; an object', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'ask', phonetic: '/ɑːsk/', meaning_zh: '问；请求', meaning_en: 'to put a question', pos: 'v', difficulty: 1, theme: 'daily' },
  // —— study / school ——
  { word: 'attention', phonetic: '/əˈtenʃn/', meaning_zh: '注意', meaning_en: 'notice or interest', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning_zh: '可获得的', meaning_en: 'able to be used or got', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning_zh: '平均的；普通的', meaning_en: 'typical; mean value', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning_zh: '避免', meaning_en: 'to keep away from', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'aware', phonetic: '/əˈweə(r)/', meaning_zh: '意识到的', meaning_en: 'knowing about something', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'basic', phonetic: '/ˈbeɪsɪk/', meaning_zh: '基本的', meaning_en: 'forming the main part; simple', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'because', phonetic: '/bɪˈkɒz/', meaning_zh: '因为', meaning_en: 'for the reason that', pos: 'conj', difficulty: 1, theme: 'daily' },
  { word: 'become', phonetic: '/bɪˈkʌm/', meaning_zh: '成为', meaning_en: 'to start to be', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'before', phonetic: '/bɪˈfɔː(r)/', meaning_zh: '在…之前', meaning_en: 'earlier than', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'begin', phonetic: '/bɪˈɡɪn/', meaning_zh: '开始', meaning_en: 'to start', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'believe', phonetic: '/bɪˈliːv/', meaning_zh: '相信', meaning_en: 'to think something is true', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning_zh: '益处；受益', meaning_en: 'an advantage; to gain', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'between', phonetic: '/bɪˈtwiːn/', meaning_zh: '在…之间', meaning_en: 'in the space separating two things', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'beyond', phonetic: '/bɪˈjɒnd/', meaning_zh: '超出；在…之外', meaning_en: 'further than; more than', pos: 'prep', difficulty: 2, theme: 'study' },
  { word: 'board', phonetic: '/bɔːd/', meaning_zh: '木板；董事会；登机', meaning_en: 'a flat piece of wood; to get on a plane', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'body', phonetic: '/ˈbɒdi/', meaning_zh: '身体', meaning_en: 'the physical structure of a person', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'both', phonetic: '/bəʊθ/', meaning_zh: '两者都', meaning_en: 'the two; the one and the other', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'break', phonetic: '/breɪk/', meaning_zh: '打破；休息', meaning_en: 'to separate into pieces; a pause', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'bright', phonetic: '/braɪt/', meaning_zh: '明亮的；聪明的', meaning_en: 'full of light; intelligent', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'bring', phonetic: '/brɪŋ/', meaning_zh: '带来', meaning_en: 'to take something with you', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'build', phonetic: '/bɪld/', meaning_zh: '建造', meaning_en: 'to make by putting parts together', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'business', phonetic: '/ˈbɪznəs/', meaning_zh: '商业；事务', meaning_en: 'trade; a company', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'busy', phonetic: '/ˈbɪzi/', meaning_zh: '忙碌的', meaning_en: 'having a lot to do', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'buy', phonetic: '/baɪ/', meaning_zh: '购买', meaning_en: 'to get by paying money', pos: 'v', difficulty: 1, theme: 'daily' },
  // —— work / career ——
  { word: 'career', phonetic: '/kəˈrɪə(r)/', meaning_zh: '职业；生涯', meaning_en: 'a job or series of jobs over time', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'careful', phonetic: '/ˈkeəfl/', meaning_zh: '小心的', meaning_en: 'giving attention to avoid harm', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'cause', phonetic: '/kɔːz/', meaning_zh: '导致；原因', meaning_en: 'to make happen; a reason', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'certain', phonetic: '/ˈsɜːtn/', meaning_zh: '确定的；某个', meaning_en: 'sure; particular', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'chance', phonetic: '/tʃɑːns/', meaning_zh: '机会', meaning_en: 'a possibility; an opportunity', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'change', phonetic: '/tʃeɪndʒ/', meaning_zh: '改变；零钱', meaning_en: 'to make different; coins', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'charge', phonetic: '/tʃɑːdʒ/', meaning_zh: '收费；充电；指控', meaning_en: 'to ask for money; to accuse', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'check', phonetic: '/tʃek/', meaning_zh: '检查；核对', meaning_en: 'to examine for correctness', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'choice', phonetic: '/tʃɔɪs/', meaning_zh: '选择', meaning_en: 'an act of choosing', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'choose', phonetic: '/tʃuːz/', meaning_zh: '选择', meaning_en: 'to pick from options', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'city', phonetic: '/ˈsɪti/', meaning_zh: '城市', meaning_en: 'a large town', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'claim', phonetic: '/kleɪm/', meaning_zh: '声称；索赔', meaning_en: 'to say something is true', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'clear', phonetic: '/klɪə(r)/', meaning_zh: '清晰的；清除', meaning_en: 'easy to understand; to remove', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'close', phonetic: '/kləʊs/', meaning_zh: '近的；关闭', meaning_en: 'near; to shut', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'collect', phonetic: '/kəˈlekt/', meaning_zh: '收集', meaning_en: 'to bring things together', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'common', phonetic: '/ˈkɒmən/', meaning_zh: '常见的；共同的', meaning_en: 'happening often; shared', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'community', phonetic: '/kəˈmjuːnəti/', meaning_zh: '社区；群体', meaning_en: 'people living in one area', pos: 'n', difficulty: 2, theme: 'daily' },
  { word: 'company', phonetic: '/ˈkʌmpəni/', meaning_zh: '公司；陪伴', meaning_en: 'a business organization', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'compare', phonetic: '/kəmˈpeə(r)/', meaning_zh: '比较', meaning_en: 'to examine similarities and differences', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'complete', phonetic: '/kəmˈpliːt/', meaning_zh: '完成；完整的', meaning_en: 'to finish; whole', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning_zh: '条件；状况', meaning_en: 'the state of something', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'consider', phonetic: '/kənˈsɪdə(r)/', meaning_zh: '考虑', meaning_en: 'to think carefully about', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning_zh: '继续', meaning_en: 'to keep doing', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'control', phonetic: '/kənˈtrəʊl/', meaning_zh: '控制', meaning_en: 'to have power over', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'cost', phonetic: '/kɒst/', meaning_zh: '花费；成本', meaning_en: 'the price of something', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'could', phonetic: '/kʊd/', meaning_zh: '能够（过去/委婉）', meaning_en: 'past of can; polite can', pos: 'modal', difficulty: 1, theme: 'daily' },
  { word: 'country', phonetic: '/ˈkʌntri/', meaning_zh: '国家；乡村', meaning_en: 'a nation; rural area', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'course', phonetic: '/kɔːs/', meaning_zh: '课程；过程', meaning_en: 'a series of lessons; path', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'create', phonetic: '/kriˈeɪt/', meaning_zh: '创造', meaning_en: 'to make something new', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'culture', phonetic: '/ˈkʌltʃə(r)/', meaning_zh: '文化', meaning_en: 'customs and arts of a group', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'current', phonetic: '/ˈkʌrənt/', meaning_zh: '当前的；水流', meaning_en: 'happening now', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'customer', phonetic: '/ˈkʌstəmə(r)/', meaning_zh: '顾客', meaning_en: 'a person who buys goods', pos: 'n', difficulty: 1, theme: 'work' },
  // —— emotion / people ——
  { word: 'danger', phonetic: '/ˈdeɪndʒə(r)/', meaning_zh: '危险', meaning_en: 'the possibility of harm', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'decide', phonetic: '/dɪˈsaɪd/', meaning_zh: '决定', meaning_en: 'to make a choice', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'decision', phonetic: '/dɪˈsɪʒn/', meaning_zh: '决定', meaning_en: 'a choice made after thinking', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'deep', phonetic: '/diːp/', meaning_zh: '深的', meaning_en: 'going far down', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'describe', phonetic: '/dɪˈskraɪb/', meaning_zh: '描述', meaning_en: 'to say what something is like', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'design', phonetic: '/dɪˈzaɪn/', meaning_zh: '设计', meaning_en: 'to plan how something looks', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'develop', phonetic: '/dɪˈveləp/', meaning_zh: '发展；开发', meaning_en: 'to grow or improve', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'difference', phonetic: '/ˈdɪfrəns/', meaning_zh: '差异', meaning_en: 'a way in which things are not the same', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'different', phonetic: '/ˈdɪfrənt/', meaning_zh: '不同的', meaning_en: 'not the same', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'difficult', phonetic: '/ˈdɪfɪkəlt/', meaning_zh: '困难的', meaning_en: 'hard to do or understand', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'direct', phonetic: '/dəˈrekt/', meaning_zh: '直接的；指导', meaning_en: 'straight; to control', pos: 'adj', difficulty: 2, theme: 'work' },
  { word: 'discuss', phonetic: '/dɪˈskʌs/', meaning_zh: '讨论', meaning_en: 'to talk about something', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'during', phonetic: '/ˈdjʊərɪŋ/', meaning_zh: '在…期间', meaning_en: 'throughout a period of time', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'early', phonetic: '/ˈɜːli/', meaning_zh: '早的', meaning_en: 'near the beginning of a period', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'earth', phonetic: '/ɜːθ/', meaning_zh: '地球；泥土', meaning_en: 'the planet we live on', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'easy', phonetic: '/ˈiːzi/', meaning_zh: '容易的', meaning_en: 'not hard to do', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', meaning_zh: '教育', meaning_en: 'the process of teaching and learning', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'effect', phonetic: '/ɪˈfekt/', meaning_zh: '影响；效果', meaning_en: 'a result or change', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'effort', phonetic: '/ˈefət/', meaning_zh: '努力', meaning_en: 'physical or mental energy used', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'either', phonetic: '/ˈaɪðə(r)/', meaning_zh: '任一；也（否定）', meaning_en: 'one or the other', pos: 'det', difficulty: 2, theme: 'daily' },
  { word: 'else', phonetic: '/els/', meaning_zh: '其他', meaning_en: 'in addition; different', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'energy', phonetic: '/ˈenədʒi/', meaning_zh: '能量；精力', meaning_en: 'power to do work; vitality', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', meaning_zh: '享受；喜欢', meaning_en: 'to get pleasure from', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'enough', phonetic: '/ɪˈnʌf/', meaning_zh: '足够的', meaning_en: 'as much as needed', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'enter', phonetic: '/ˈentə(r)/', meaning_zh: '进入', meaning_en: 'to go into', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'entire', phonetic: '/ɪnˈtaɪə(r)/', meaning_zh: '整个的', meaning_en: 'whole; complete', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning_zh: '环境', meaning_en: 'the surroundings or conditions', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'especially', phonetic: '/ɪˈspeʃəli/', meaning_zh: '尤其', meaning_en: 'more than usual', pos: 'adv', difficulty: 2, theme: 'study' },
  { word: 'even', phonetic: '/ˈiːvn/', meaning_zh: '甚至；偶数', meaning_en: 'used for emphasis', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'event', phonetic: '/ɪˈvent/', meaning_zh: '事件；活动', meaning_en: 'something that happens', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'ever', phonetic: '/ˈevə(r)/', meaning_zh: '曾经；永远', meaning_en: 'at any time', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'every', phonetic: '/ˈevri/', meaning_zh: '每个', meaning_en: 'all of a group', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'example', phonetic: '/ɪɡˈzɑːmpl/', meaning_zh: '例子', meaning_en: 'something that shows a rule', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'except', phonetic: '/ɪkˈsept/', meaning_zh: '除了', meaning_en: 'not including', pos: 'prep', difficulty: 2, theme: 'study' },
  { word: 'expect', phonetic: '/ɪkˈspekt/', meaning_zh: '期待；预计', meaning_en: 'to think something will happen', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning_zh: '经验；经历', meaning_en: 'knowledge from doing; an event', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'explain', phonetic: '/ɪkˈspleɪn/', meaning_zh: '解释', meaning_en: 'to make clear', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'express', phonetic: '/ɪkˈspres/', meaning_zh: '表达；快递', meaning_en: 'to show a feeling or idea', pos: 'v', difficulty: 2, theme: 'study' },
  // —— game / competition (brand theme) ——
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning_zh: '实现；达到', meaning_en: 'to succeed in doing something', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning_zh: '挑战', meaning_en: 'a difficult task or situation', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'compete', phonetic: '/kəmˈpiːt/', meaning_zh: '竞争；比赛', meaning_en: 'to try to win against others', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'victory', phonetic: '/ˈvɪktəri/', meaning_zh: '胜利', meaning_en: 'success in a battle or competition', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'strategy', phonetic: '/ˈstrætədʒi/', meaning_zh: '策略', meaning_en: 'a plan to achieve a goal', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'focus', phonetic: '/ˈfəʊkəs/', meaning_zh: '专注；焦点', meaning_en: 'to give attention to something', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning_zh: '改进；提高', meaning_en: 'to make or become better', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'practice', phonetic: '/ˈpræktɪs/', meaning_zh: '练习；实践', meaning_en: 'to do something regularly to improve', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'master', phonetic: '/ˈmɑːstə(r)/', meaning_zh: '精通；掌握', meaning_en: 'to learn completely', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'rank', phonetic: '/ræŋk/', meaning_zh: '排名；等级', meaning_en: 'a position in a scale', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'reward', phonetic: '/rɪˈwɔːd/', meaning_zh: '奖励', meaning_en: 'something given for effort or achievement', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'streak', phonetic: '/striːk/', meaning_zh: '连续；连胜', meaning_en: 'a continuous series of successes', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'pressure', phonetic: '/ˈpreʃə(r)/', meaning_zh: '压力', meaning_en: 'stress caused by urgent demands', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'confident', phonetic: '/ˈkɒnfɪdənt/', meaning_zh: '自信的', meaning_en: 'sure of yourself', pos: 'adj', difficulty: 2, theme: 'game' },
  { word: 'opponent', phonetic: '/əˈpəʊnənt/', meaning_zh: '对手', meaning_en: 'someone you compete against', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning_zh: '前进；提升', meaning_en: 'to move forward or progress', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning_zh: '击败；失败', meaning_en: 'to win against someone', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'survive', phonetic: '/səˈvaɪv/', meaning_zh: '幸存；挺过', meaning_en: 'to continue to live or exist', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning_zh: '冠军', meaning_en: 'the winner of a competition', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'battle', phonetic: '/ˈbætl/', meaning_zh: '战斗；较量', meaning_en: 'a fight or contest', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', meaning_zh: '淘汰；消除', meaning_en: 'to remove or knock out of a contest', pos: 'v', difficulty: 3, theme: 'game' },
  { word: 'qualify', phonetic: '/ˈkwɒlɪfaɪ/', meaning_zh: '取得资格', meaning_en: 'to earn the right to enter the next stage', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'momentum', phonetic: '/məˈmentəm/', meaning_zh: '势头；动力', meaning_en: 'the force that keeps something developing', pos: 'n', difficulty: 3, theme: 'game' },
  { word: 'resilient', phonetic: '/rɪˈzɪliənt/', meaning_zh: '有韧性的', meaning_en: 'able to recover quickly from difficulty', pos: 'adj', difficulty: 3, theme: 'game' },
  { word: 'precise', phonetic: '/prɪˈsaɪs/', meaning_zh: '精确的', meaning_en: 'exact and accurate', pos: 'adj', difficulty: 2, theme: 'game' },
  { word: 'adapt', phonetic: '/əˈdæpt/', meaning_zh: '适应', meaning_en: 'to change to fit new conditions', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'clutch', phonetic: '/klʌtʃ/', meaning_zh: '关键时刻；关键发挥', meaning_en: 'to perform well under pressure', pos: 'v', difficulty: 3, theme: 'game' },
  { word: 'dominate', phonetic: '/ˈdɒmɪneɪt/', meaning_zh: '主宰；统治', meaning_en: 'to have control or be the strongest', pos: 'v', difficulty: 2, theme: 'game' },
  { word: 'tactical', phonetic: '/ˈtæktɪkl/', meaning_zh: '战术的', meaning_en: 'related to planned actions in a contest', pos: 'adj', difficulty: 3, theme: 'game' },
  { word: 'endurance', phonetic: '/ɪnˈdjʊərəns/', meaning_zh: '耐力', meaning_en: 'the ability to keep going for a long time', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'intense', phonetic: '/ɪnˈtens/', meaning_zh: '激烈的；强烈的', meaning_en: 'very strong or extreme', pos: 'adj', difficulty: 2, theme: 'game' },
  { word: 'objective', phonetic: '/əbˈdʒektɪv/', meaning_zh: '目标；客观的', meaning_en: 'a goal you aim to achieve', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'outplay', phonetic: '/ˌaʊtˈpleɪ/', meaning_zh: '打得比…好', meaning_en: 'to play better than an opponent', pos: 'v', difficulty: 3, theme: 'game' },
  { word: 'comeback', phonetic: '/ˈkʌmbæk/', meaning_zh: '逆转；东山再起', meaning_en: 'a return to success after failure', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'discipline', phonetic: '/ˈdɪsəplɪn/', meaning_zh: '纪律；自律', meaning_en: 'training to obey rules or control yourself', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'execute', phonetic: '/ˈeksɪkjuːt/', meaning_zh: '执行；完成', meaning_en: 'to carry out a plan skillfully', pos: 'v', difficulty: 3, theme: 'game' },
  { word: 'instinct', phonetic: '/ˈɪnstɪŋkt/', meaning_zh: '直觉；本能', meaning_en: 'a natural ability to react without thinking', pos: 'n', difficulty: 3, theme: 'game' },
  { word: 'rivalry', phonetic: '/ˈraɪvlri/', meaning_zh: '竞争关系', meaning_en: 'competition between people or teams', pos: 'n', difficulty: 3, theme: 'game' },
  { word: 'underdog', phonetic: '/ˈʌndədɒɡ/', meaning_zh: '弱旅；不被看好者', meaning_en: 'a competitor expected to lose', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'climax', phonetic: '/ˈklaɪmæks/', meaning_zh: '高潮；顶点', meaning_en: 'the most exciting or important point', pos: 'n', difficulty: 2, theme: 'game' },
  // —— more intermediate ——
  { word: 'factor', phonetic: '/ˈfæktə(r)/', meaning_zh: '因素', meaning_en: 'something that influences a result', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'fail', phonetic: '/feɪl/', meaning_zh: '失败', meaning_en: 'to not succeed', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'famous', phonetic: '/ˈfeɪməs/', meaning_zh: '著名的', meaning_en: 'known by many people', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'far', phonetic: '/fɑː(r)/', meaning_zh: '远的', meaning_en: 'at a great distance', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'feel', phonetic: '/fiːl/', meaning_zh: '感觉', meaning_en: 'to experience an emotion or touch', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'field', phonetic: '/fiːld/', meaning_zh: '田野；领域', meaning_en: 'an open area; a subject of study', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'figure', phonetic: '/ˈfɪɡə(r)/', meaning_zh: '数字；人物；认为', meaning_en: 'a number; a person; to think', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'final', phonetic: '/ˈfaɪnl/', meaning_zh: '最终的；决赛', meaning_en: 'last; the last game', pos: 'adj', difficulty: 1, theme: 'game' },
  { word: 'finance', phonetic: '/ˈfaɪnæns/', meaning_zh: '金融；财政', meaning_en: 'money management', pos: 'n', difficulty: 3, theme: 'work' },
  { word: 'find', phonetic: '/faɪnd/', meaning_zh: '找到', meaning_en: 'to discover or locate', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'finish', phonetic: '/ˈfɪnɪʃ/', meaning_zh: '完成', meaning_en: 'to bring to an end', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'follow', phonetic: '/ˈfɒləʊ/', meaning_zh: '跟随；遵循', meaning_en: 'to go after; to obey', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'force', phonetic: '/fɔːs/', meaning_zh: '力量；强迫', meaning_en: 'strength; to make someone do', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'foreign', phonetic: '/ˈfɒrən/', meaning_zh: '外国的', meaning_en: 'from another country', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'forget', phonetic: '/fəˈɡet/', meaning_zh: '忘记', meaning_en: 'to fail to remember', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'form', phonetic: '/fɔːm/', meaning_zh: '形式；形成', meaning_en: 'shape; to create', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'free', phonetic: '/friː/', meaning_zh: '自由的；免费的', meaning_en: 'not controlled; costing nothing', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'friend', phonetic: '/frend/', meaning_zh: '朋友', meaning_en: 'a person you like and know well', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'full', phonetic: '/fʊl/', meaning_zh: '满的', meaning_en: 'containing as much as possible', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'future', phonetic: '/ˈfjuːtʃə(r)/', meaning_zh: '未来', meaning_en: 'the time after now', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'general', phonetic: '/ˈdʒenrəl/', meaning_zh: '一般的；将军', meaning_en: 'not detailed; overall', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'goal', phonetic: '/ɡəʊl/', meaning_zh: '目标；进球', meaning_en: 'something you want to achieve', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'government', phonetic: '/ˈɡʌvənmənt/', meaning_zh: '政府', meaning_en: 'the group that runs a country', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'great', phonetic: '/ɡreɪt/', meaning_zh: '伟大的；极好的', meaning_en: 'very good or large', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'group', phonetic: '/ɡruːp/', meaning_zh: '群体；组', meaning_en: 'a number of people or things together', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'grow', phonetic: '/ɡrəʊ/', meaning_zh: '生长；增长', meaning_en: 'to become larger or develop', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'guess', phonetic: '/ɡes/', meaning_zh: '猜测', meaning_en: 'to give an answer without certainty', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'guide', phonetic: '/ɡaɪd/', meaning_zh: '指导；向导', meaning_en: 'to show the way; a person who leads', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'happen', phonetic: '/ˈhæpən/', meaning_zh: '发生', meaning_en: 'to take place', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'happy', phonetic: '/ˈhæpi/', meaning_zh: '快乐的', meaning_en: 'feeling pleasure', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'hard', phonetic: '/hɑːd/', meaning_zh: '困难的；努力地', meaning_en: 'difficult; with effort', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'health', phonetic: '/helθ/', meaning_zh: '健康', meaning_en: 'the condition of the body or mind', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'hear', phonetic: '/hɪə(r)/', meaning_zh: '听见', meaning_en: 'to perceive sound', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'help', phonetic: '/help/', meaning_zh: '帮助', meaning_en: 'to make it easier for someone', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'high', phonetic: '/haɪ/', meaning_zh: '高的', meaning_en: 'having a large distance from bottom to top', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'history', phonetic: '/ˈhɪstri/', meaning_zh: '历史', meaning_en: 'the study of past events', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'hold', phonetic: '/həʊld/', meaning_zh: '握住；举行', meaning_en: 'to keep in the hand; to organize', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'hope', phonetic: '/həʊp/', meaning_zh: '希望', meaning_en: 'to want something to happen', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'however', phonetic: '/haʊˈevə(r)/', meaning_zh: '然而', meaning_en: 'but; nevertheless', pos: 'adv', difficulty: 2, theme: 'study' },
  { word: 'human', phonetic: '/ˈhjuːmən/', meaning_zh: '人类的；人', meaning_en: 'relating to people', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'idea', phonetic: '/aɪˈdɪə/', meaning_zh: '想法；主意', meaning_en: 'a thought or plan', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'identify', phonetic: '/aɪˈdentɪfaɪ/', meaning_zh: '识别；确认', meaning_en: 'to recognize or name', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'image', phonetic: '/ˈɪmɪdʒ/', meaning_zh: '图像；形象', meaning_en: 'a picture or likeness', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning_zh: '想象', meaning_en: 'to form a picture in the mind', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'important', phonetic: '/ɪmˈpɔːtnt/', meaning_zh: '重要的', meaning_en: 'of great value or influence', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'include', phonetic: '/ɪnˈkluːd/', meaning_zh: '包括', meaning_en: 'to contain as part of a whole', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'increase', phonetic: '/ɪnˈkriːs/', meaning_zh: '增加', meaning_en: 'to become or make greater', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'indicate', phonetic: '/ˈɪndɪkeɪt/', meaning_zh: '表明；指示', meaning_en: 'to show or point out', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'individual', phonetic: '/ˌɪndɪˈvɪdʒuəl/', meaning_zh: '个人；个别的', meaning_en: 'a single person; separate', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'industry', phonetic: '/ˈɪndəstri/', meaning_zh: '工业；行业', meaning_en: 'production of goods; a business field', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'information', phonetic: '/ˌɪnfəˈmeɪʃn/', meaning_zh: '信息', meaning_en: 'facts or details about something', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'instead', phonetic: '/ɪnˈsted/', meaning_zh: '代替；反而', meaning_en: 'as an alternative', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'interest', phonetic: '/ˈɪntrəst/', meaning_zh: '兴趣；利息', meaning_en: 'wanting to know more; money paid on a loan', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'international', phonetic: '/ˌɪntəˈnæʃnəl/', meaning_zh: '国际的', meaning_en: 'involving more than one country', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'interview', phonetic: '/ˈɪntəvjuː/', meaning_zh: '面试；采访', meaning_en: 'a formal meeting for a job or news', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'involve', phonetic: '/ɪnˈvɒlv/', meaning_zh: '涉及；使参与', meaning_en: 'to include as a necessary part', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'issue', phonetic: '/ˈɪʃuː/', meaning_zh: '问题；议题', meaning_en: 'an important topic or problem', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'item', phonetic: '/ˈaɪtəm/', meaning_zh: '项目；一件', meaning_en: 'a single thing in a list', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'join', phonetic: '/dʒɔɪn/', meaning_zh: '加入；连接', meaning_en: 'to become a member; to connect', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'keep', phonetic: '/kiːp/', meaning_zh: '保持；保留', meaning_en: 'to continue to have', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'kind', phonetic: '/kaɪnd/', meaning_zh: '种类；友好的', meaning_en: 'a type; friendly', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning_zh: '知识', meaning_en: 'information and understanding', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'language', phonetic: '/ˈlæŋɡwɪdʒ/', meaning_zh: '语言', meaning_en: 'a system of communication', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'large', phonetic: '/lɑːdʒ/', meaning_zh: '大的', meaning_en: 'big in size or amount', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'last', phonetic: '/lɑːst/', meaning_zh: '最后的；持续', meaning_en: 'final; to continue', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'late', phonetic: '/leɪt/', meaning_zh: '晚的', meaning_en: 'after the usual time', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'laugh', phonetic: '/lɑːf/', meaning_zh: '笑', meaning_en: 'to make sounds of amusement', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'law', phonetic: '/lɔː/', meaning_zh: '法律', meaning_en: 'rules of a country', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'lead', phonetic: '/liːd/', meaning_zh: '领导；领先', meaning_en: 'to guide; to be in front', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'learn', phonetic: '/lɜːn/', meaning_zh: '学习', meaning_en: 'to gain knowledge or skill', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'leave', phonetic: '/liːv/', meaning_zh: '离开；留下', meaning_en: 'to go away from; to let remain', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'level', phonetic: '/ˈlevl/', meaning_zh: '水平；等级', meaning_en: 'a position on a scale', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'life', phonetic: '/laɪf/', meaning_zh: '生活；生命', meaning_en: 'the state of being alive; living', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'light', phonetic: '/laɪt/', meaning_zh: '光；轻的', meaning_en: 'brightness; not heavy', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'likely', phonetic: '/ˈlaɪkli/', meaning_zh: '可能的', meaning_en: 'probable', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'limit', phonetic: '/ˈlɪmɪt/', meaning_zh: '限制；限度', meaning_en: 'a point beyond which you cannot go', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'listen', phonetic: '/ˈlɪsn/', meaning_zh: '听', meaning_en: 'to pay attention to sound', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'little', phonetic: '/ˈlɪtl/', meaning_zh: '小的；少的', meaning_en: 'small; not much', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'local', phonetic: '/ˈləʊkl/', meaning_zh: '当地的', meaning_en: 'relating to a particular area', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'long', phonetic: '/lɒŋ/', meaning_zh: '长的', meaning_en: 'measuring a great distance', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'look', phonetic: '/lʊk/', meaning_zh: '看；看起来', meaning_en: 'to use your eyes; to appear', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'lose', phonetic: '/luːz/', meaning_zh: '失去；输掉', meaning_en: 'to no longer have; to fail to win', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'love', phonetic: '/lʌv/', meaning_zh: '爱', meaning_en: 'a strong feeling of affection', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'main', phonetic: '/meɪn/', meaning_zh: '主要的', meaning_en: 'most important', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'major', phonetic: '/ˈmeɪdʒə(r)/', meaning_zh: '主要的；专业', meaning_en: 'important; a subject of study', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'make', phonetic: '/meɪk/', meaning_zh: '制作；使得', meaning_en: 'to create; to cause to be', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'manage', phonetic: '/ˈmænɪdʒ/', meaning_zh: '管理；设法做到', meaning_en: 'to control or succeed in doing', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'market', phonetic: '/ˈmɑːkɪt/', meaning_zh: '市场', meaning_en: 'a place to buy and sell', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'material', phonetic: '/məˈtɪəriəl/', meaning_zh: '材料；物质的', meaning_en: 'what something is made of', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'matter', phonetic: '/ˈmætə(r)/', meaning_zh: '事情；要紧', meaning_en: 'a subject; to be important', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'maybe', phonetic: '/ˈmeɪbi/', meaning_zh: '也许', meaning_en: 'perhaps', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'mean', phonetic: '/miːn/', meaning_zh: '意思是；吝啬的', meaning_en: 'to express; unkind', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'measure', phonetic: '/ˈmeʒə(r)/', meaning_zh: '测量；措施', meaning_en: 'to find the size; an action', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'media', phonetic: '/ˈmiːdiə/', meaning_zh: '媒体', meaning_en: 'TV, newspapers, internet news', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'meet', phonetic: '/miːt/', meaning_zh: '遇见；开会', meaning_en: 'to come together', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'member', phonetic: '/ˈmembə(r)/', meaning_zh: '成员', meaning_en: 'a person in a group', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'memory', phonetic: '/ˈmeməri/', meaning_zh: '记忆', meaning_en: 'the ability to remember', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'mention', phonetic: '/ˈmenʃn/', meaning_zh: '提及', meaning_en: 'to speak about briefly', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'method', phonetic: '/ˈmeθəd/', meaning_zh: '方法', meaning_en: 'a way of doing something', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'middle', phonetic: '/ˈmɪdl/', meaning_zh: '中间', meaning_en: 'the central part', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'might', phonetic: '/maɪt/', meaning_zh: '可能；力量', meaning_en: 'expressing possibility', pos: 'modal', difficulty: 1, theme: 'daily' },
  { word: 'mind', phonetic: '/maɪnd/', meaning_zh: '头脑；介意', meaning_en: 'the part that thinks; to care', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'minute', phonetic: '/ˈmɪnɪt/', meaning_zh: '分钟', meaning_en: 'sixty seconds', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'miss', phonetic: '/mɪs/', meaning_zh: '错过；想念', meaning_en: 'to fail to hit or catch; to feel sad without', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'model', phonetic: '/ˈmɒdl/', meaning_zh: '模型；模特', meaning_en: 'a copy; a fashion person', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'modern', phonetic: '/ˈmɒdn/', meaning_zh: '现代的', meaning_en: 'of the present time', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'moment', phonetic: '/ˈməʊmənt/', meaning_zh: '片刻；时刻', meaning_en: 'a very short time', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'money', phonetic: '/ˈmʌni/', meaning_zh: '钱', meaning_en: 'coins and notes used to buy', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'month', phonetic: '/mʌnθ/', meaning_zh: '月', meaning_en: 'about 30 days', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'more', phonetic: '/mɔː(r)/', meaning_zh: '更多', meaning_en: 'a greater amount', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'morning', phonetic: '/ˈmɔːnɪŋ/', meaning_zh: '早晨', meaning_en: 'the early part of the day', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'most', phonetic: '/məʊst/', meaning_zh: '最多；大多数', meaning_en: 'nearly all; the greatest amount', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'move', phonetic: '/muːv/', meaning_zh: '移动；搬家', meaning_en: 'to change position', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'music', phonetic: '/ˈmjuːzɪk/', meaning_zh: '音乐', meaning_en: 'sounds arranged to be pleasant', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'must', phonetic: '/mʌst/', meaning_zh: '必须', meaning_en: 'to be necessary or required', pos: 'modal', difficulty: 1, theme: 'daily' },
  { word: 'name', phonetic: '/neɪm/', meaning_zh: '名字', meaning_en: 'what a person or thing is called', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'nation', phonetic: '/ˈneɪʃn/', meaning_zh: '国家；民族', meaning_en: 'a country and its people', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'natural', phonetic: '/ˈnætʃrəl/', meaning_zh: '自然的', meaning_en: 'existing in nature; not artificial', pos: 'adj', difficulty: 1, theme: 'study' },
  { word: 'nature', phonetic: '/ˈneɪtʃə(r)/', meaning_zh: '自然；本质', meaning_en: 'the physical world; character', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'near', phonetic: '/nɪə(r)/', meaning_zh: '近的', meaning_en: 'not far away', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'need', phonetic: '/niːd/', meaning_zh: '需要', meaning_en: 'to require', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'never', phonetic: '/ˈnevə(r)/', meaning_zh: '从不', meaning_en: 'not at any time', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'new', phonetic: '/njuː/', meaning_zh: '新的', meaning_en: 'not existing before; recent', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'next', phonetic: '/nekst/', meaning_zh: '下一个', meaning_en: 'coming immediately after', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'night', phonetic: '/naɪt/', meaning_zh: '夜晚', meaning_en: 'the time of darkness', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'nothing', phonetic: '/ˈnʌθɪŋ/', meaning_zh: '没有东西', meaning_en: 'not anything', pos: 'pron', difficulty: 1, theme: 'daily' },
  { word: 'notice', phonetic: '/ˈnəʊtɪs/', meaning_zh: '注意到；通知', meaning_en: 'to see; a written announcement', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'number', phonetic: '/ˈnʌmbə(r)/', meaning_zh: '数字；号码', meaning_en: 'a figure used for counting', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'offer', phonetic: '/ˈɒfə(r)/', meaning_zh: '提供；报价', meaning_en: 'to present for acceptance', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'office', phonetic: '/ˈɒfɪs/', meaning_zh: '办公室', meaning_en: 'a place for business work', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'often', phonetic: '/ˈɒfn/', meaning_zh: '经常', meaning_en: 'many times', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'once', phonetic: '/wʌns/', meaning_zh: '一次；曾经', meaning_en: 'one time; at some time in the past', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'only', phonetic: '/ˈəʊnli/', meaning_zh: '仅仅；唯一的', meaning_en: 'no more than; sole', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'open', phonetic: '/ˈəʊpən/', meaning_zh: '打开；开放的', meaning_en: 'not closed; to make free', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'order', phonetic: '/ˈɔːdə(r)/', meaning_zh: '顺序；订单；命令', meaning_en: 'arrangement; a request to buy', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'other', phonetic: '/ˈʌðə(r)/', meaning_zh: '其他的', meaning_en: 'different or additional', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'outside', phonetic: '/ˌaʊtˈsaɪd/', meaning_zh: '外面', meaning_en: 'not inside', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'own', phonetic: '/əʊn/', meaning_zh: '自己的；拥有', meaning_en: 'belonging to oneself; to possess', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'paper', phonetic: '/ˈpeɪpə(r)/', meaning_zh: '纸；论文', meaning_en: 'material for writing; an essay', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'parent', phonetic: '/ˈpeərənt/', meaning_zh: '父母', meaning_en: 'a mother or father', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'part', phonetic: '/pɑːt/', meaning_zh: '部分', meaning_en: 'a piece of a whole', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'particular', phonetic: '/pəˈtɪkjələ(r)/', meaning_zh: '特定的', meaning_en: 'specific; special', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'party', phonetic: '/ˈpɑːti/', meaning_zh: '聚会；政党', meaning_en: 'a social gathering; a political group', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'pass', phonetic: '/pɑːs/', meaning_zh: '通过；传递', meaning_en: 'to go past; to succeed in a test', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'past', phonetic: '/pɑːst/', meaning_zh: '过去；经过', meaning_en: 'time before now', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'patient', phonetic: '/ˈpeɪʃnt/', meaning_zh: '有耐心的；病人', meaning_en: 'able to wait calmly; a sick person', pos: 'adj', difficulty: 2, theme: 'daily' },
  { word: 'pattern', phonetic: '/ˈpætn/', meaning_zh: '模式；图案', meaning_en: 'a repeated design or way', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'pay', phonetic: '/peɪ/', meaning_zh: '支付', meaning_en: 'to give money for something', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'people', phonetic: '/ˈpiːpl/', meaning_zh: '人们', meaning_en: 'human beings in general', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'perform', phonetic: '/pəˈfɔːm/', meaning_zh: '表演；表现', meaning_en: 'to do a task or show', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'perhaps', phonetic: '/pəˈhæps/', meaning_zh: '也许', meaning_en: 'maybe', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'period', phonetic: '/ˈpɪəriəd/', meaning_zh: '时期；课时', meaning_en: 'a length of time', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'person', phonetic: '/ˈpɜːsn/', meaning_zh: '人', meaning_en: 'a human being', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'personal', phonetic: '/ˈpɜːsənl/', meaning_zh: '个人的', meaning_en: 'belonging to a particular person', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'phone', phonetic: '/fəʊn/', meaning_zh: '电话', meaning_en: 'a device for talking over distance', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'pick', phonetic: '/pɪk/', meaning_zh: '挑选；采摘', meaning_en: 'to choose; to gather', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'picture', phonetic: '/ˈpɪktʃə(r)/', meaning_zh: '图片', meaning_en: 'a drawing or photograph', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'place', phonetic: '/pleɪs/', meaning_zh: '地方；放置', meaning_en: 'a location; to put', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'plan', phonetic: '/plæn/', meaning_zh: '计划', meaning_en: 'an arrangement for the future', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'plant', phonetic: '/plɑːnt/', meaning_zh: '植物；工厂', meaning_en: 'a living green organism; a factory', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'play', phonetic: '/pleɪ/', meaning_zh: '玩；演奏', meaning_en: 'to take part in a game', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'player', phonetic: '/ˈpleɪə(r)/', meaning_zh: '玩家；运动员', meaning_en: 'someone who plays a game', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'point', phonetic: '/pɔɪnt/', meaning_zh: '点；观点；分数', meaning_en: 'a detail; a score unit', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'policy', phonetic: '/ˈpɒləsi/', meaning_zh: '政策', meaning_en: 'a plan of action by an organization', pos: 'n', difficulty: 3, theme: 'work' },
  { word: 'political', phonetic: '/pəˈlɪtɪkl/', meaning_zh: '政治的', meaning_en: 'relating to government', pos: 'adj', difficulty: 3, theme: 'study' },
  { word: 'poor', phonetic: '/pɔː(r)/', meaning_zh: '贫穷的；差的', meaning_en: 'having little money; low quality', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'popular', phonetic: '/ˈpɒpjələ(r)/', meaning_zh: '受欢迎的', meaning_en: 'liked by many people', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'position', phonetic: '/pəˈzɪʃn/', meaning_zh: '位置；职位', meaning_en: 'a place; a job rank', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'possible', phonetic: '/ˈpɒsəbl/', meaning_zh: '可能的', meaning_en: 'able to be done or true', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'power', phonetic: '/ˈpaʊə(r)/', meaning_zh: '力量；权力', meaning_en: 'ability to do; control', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'prepare', phonetic: '/prɪˈpeə(r)/', meaning_zh: '准备', meaning_en: 'to get ready', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'present', phonetic: '/ˈpreznt/', meaning_zh: '现在的；礼物；呈现', meaning_en: 'current; a gift; to show', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'president', phonetic: '/ˈprezɪdənt/', meaning_zh: '总统；总裁', meaning_en: 'the leader of a country or company', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'press', phonetic: '/pres/', meaning_zh: '按；新闻界', meaning_en: 'to push; newspapers and media', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'pretty', phonetic: '/ˈprɪti/', meaning_zh: '漂亮的；相当', meaning_en: 'attractive; fairly', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'price', phonetic: '/praɪs/', meaning_zh: '价格', meaning_en: 'the amount of money something costs', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'private', phonetic: '/ˈpraɪvət/', meaning_zh: '私人的', meaning_en: 'not public', pos: 'adj', difficulty: 2, theme: 'work' },
  { word: 'probably', phonetic: '/ˈprɒbəbli/', meaning_zh: '很可能', meaning_en: 'almost certainly', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'problem', phonetic: '/ˈprɒbləm/', meaning_zh: '问题', meaning_en: 'a difficult situation', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'process', phonetic: '/ˈprəʊses/', meaning_zh: '过程；加工', meaning_en: 'a series of actions', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'produce', phonetic: '/prəˈdjuːs/', meaning_zh: '生产；产生', meaning_en: 'to make or create', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'product', phonetic: '/ˈprɒdʌkt/', meaning_zh: '产品', meaning_en: 'something made to be sold', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'program', phonetic: '/ˈprəʊɡræm/', meaning_zh: '节目；程序；计划', meaning_en: 'a planned series; software', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'project', phonetic: '/ˈprɒdʒekt/', meaning_zh: '项目', meaning_en: 'a planned piece of work', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'promise', phonetic: '/ˈprɒmɪs/', meaning_zh: '承诺', meaning_en: 'to say you will do something', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'protect', phonetic: '/prəˈtekt/', meaning_zh: '保护', meaning_en: 'to keep safe from harm', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'provide', phonetic: '/prəˈvaɪd/', meaning_zh: '提供', meaning_en: 'to supply something needed', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'public', phonetic: '/ˈpʌblɪk/', meaning_zh: '公共的；公众', meaning_en: 'for everyone; people in general', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'purpose', phonetic: '/ˈpɜːpəs/', meaning_zh: '目的', meaning_en: 'the reason for doing something', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'push', phonetic: '/pʊʃ/', meaning_zh: '推', meaning_en: 'to press forward', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'quality', phonetic: '/ˈkwɒləti/', meaning_zh: '质量；品质', meaning_en: 'how good or bad something is', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'question', phonetic: '/ˈkwestʃən/', meaning_zh: '问题', meaning_en: 'something you ask', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'quick', phonetic: '/kwɪk/', meaning_zh: '快的', meaning_en: 'moving or happening fast', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'quite', phonetic: '/kwaɪt/', meaning_zh: '相当；完全', meaning_en: 'fairly; completely', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'raise', phonetic: '/reɪz/', meaning_zh: '举起；提高；抚养', meaning_en: 'to lift; to increase; to bring up', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'range', phonetic: '/reɪndʒ/', meaning_zh: '范围；排列', meaning_en: 'the area between limits', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'rate', phonetic: '/reɪt/', meaning_zh: '比率；评价', meaning_en: 'a measure; to judge', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'rather', phonetic: '/ˈrɑːðə(r)/', meaning_zh: '相当；宁可', meaning_en: 'to some degree; preferably', pos: 'adv', difficulty: 2, theme: 'study' },
  { word: 'reach', phonetic: '/riːtʃ/', meaning_zh: '到达；够到', meaning_en: 'to arrive at; to stretch to', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'read', phonetic: '/riːd/', meaning_zh: '阅读', meaning_en: 'to look at and understand written words', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'ready', phonetic: '/ˈredi/', meaning_zh: '准备好的', meaning_en: 'prepared for action', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'real', phonetic: '/ˈriːəl/', meaning_zh: '真实的', meaning_en: 'actually existing', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'reason', phonetic: '/ˈriːzn/', meaning_zh: '原因；理由', meaning_en: 'why something happens', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'receive', phonetic: '/rɪˈsiːv/', meaning_zh: '收到', meaning_en: 'to get something given', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'recent', phonetic: '/ˈriːsnt/', meaning_zh: '最近的', meaning_en: 'happening not long ago', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'record', phonetic: '/ˈrekɔːd/', meaning_zh: '记录；唱片', meaning_en: 'written information; to store sound', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'reduce', phonetic: '/rɪˈdjuːs/', meaning_zh: '减少', meaning_en: 'to make smaller in amount', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'refer', phonetic: '/rɪˈfɜː(r)/', meaning_zh: '提到；参考', meaning_en: 'to mention; to look at for information', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'region', phonetic: '/ˈriːdʒən/', meaning_zh: '地区', meaning_en: 'a large area of a country', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'relate', phonetic: '/rɪˈleɪt/', meaning_zh: '联系；叙述', meaning_en: 'to connect; to tell', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'remain', phonetic: '/rɪˈmeɪn/', meaning_zh: '保持；留下', meaning_en: 'to continue to be; to stay', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'remember', phonetic: '/rɪˈmembə(r)/', meaning_zh: '记住', meaning_en: 'to keep in memory', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'report', phonetic: '/rɪˈpɔːt/', meaning_zh: '报告', meaning_en: 'to give information about', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'require', phonetic: '/rɪˈkwaɪə(r)/', meaning_zh: '需要；要求', meaning_en: 'to need; to demand', pos: 'v', difficulty: 2, theme: 'work' },
  { word: 'research', phonetic: '/rɪˈsɜːtʃ/', meaning_zh: '研究', meaning_en: 'careful study to find facts', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'resource', phonetic: '/rɪˈsɔːs/', meaning_zh: '资源', meaning_en: 'something useful available', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'respect', phonetic: '/rɪˈspekt/', meaning_zh: '尊重', meaning_en: 'admiration for someone', pos: 'n', difficulty: 2, theme: 'daily' },
  { word: 'response', phonetic: '/rɪˈspɒns/', meaning_zh: '回应', meaning_en: 'an answer or reaction', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'result', phonetic: '/rɪˈzʌlt/', meaning_zh: '结果', meaning_en: 'something that happens because of', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'return', phonetic: '/rɪˈtɜːn/', meaning_zh: '返回；归还', meaning_en: 'to go back; to give back', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'right', phonetic: '/raɪt/', meaning_zh: '正确的；右边；权利', meaning_en: 'correct; opposite of left', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'risk', phonetic: '/rɪsk/', meaning_zh: '风险', meaning_en: 'the chance of something bad', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'role', phonetic: '/rəʊl/', meaning_zh: '角色；作用', meaning_en: 'a part played; a function', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'room', phonetic: '/ruːm/', meaning_zh: '房间；空间', meaning_en: 'a space in a building', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'rule', phonetic: '/ruːl/', meaning_zh: '规则；统治', meaning_en: 'an official instruction', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'run', phonetic: '/rʌn/', meaning_zh: '跑；经营', meaning_en: 'to move fast on foot; to manage', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'safe', phonetic: '/seɪf/', meaning_zh: '安全的', meaning_en: 'not in danger', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'same', phonetic: '/seɪm/', meaning_zh: '相同的', meaning_en: 'not different', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'save', phonetic: '/seɪv/', meaning_zh: '拯救；节省；保存', meaning_en: 'to rescue; to keep for later', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'scene', phonetic: '/siːn/', meaning_zh: '场景；现场', meaning_en: 'a place where something happens', pos: 'n', difficulty: 2, theme: 'daily' },
  { word: 'school', phonetic: '/skuːl/', meaning_zh: '学校', meaning_en: 'a place for education', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'science', phonetic: '/ˈsaɪəns/', meaning_zh: '科学', meaning_en: 'study of the natural world', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'score', phonetic: '/skɔː(r)/', meaning_zh: '得分；分数', meaning_en: 'points in a game', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'search', phonetic: '/sɜːtʃ/', meaning_zh: '搜索', meaning_en: 'to look carefully for', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'season', phonetic: '/ˈsiːzn/', meaning_zh: '季节；赛季', meaning_en: 'a part of the year; a sports period', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'second', phonetic: '/ˈsekənd/', meaning_zh: '第二；秒', meaning_en: 'after the first; 1/60 of a minute', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'section', phonetic: '/ˈsekʃn/', meaning_zh: '部分；章节', meaning_en: 'a part of something', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'security', phonetic: '/sɪˈkjʊərəti/', meaning_zh: '安全；保安', meaning_en: 'protection from danger', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'seem', phonetic: '/siːm/', meaning_zh: '似乎', meaning_en: 'to appear to be', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'sell', phonetic: '/sel/', meaning_zh: '卖', meaning_en: 'to give for money', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'send', phonetic: '/send/', meaning_zh: '发送', meaning_en: 'to cause to go somewhere', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'sense', phonetic: '/sens/', meaning_zh: '感觉；意义', meaning_en: 'a feeling; meaning', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'series', phonetic: '/ˈsɪəriːz/', meaning_zh: '系列', meaning_en: 'a number of similar things in order', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'serious', phonetic: '/ˈsɪəriəs/', meaning_zh: '严肃的；严重的', meaning_en: 'not joking; important', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'serve', phonetic: '/sɜːv/', meaning_zh: '服务；发球', meaning_en: 'to provide for; to start play', pos: 'v', difficulty: 1, theme: 'work' },
  { word: 'service', phonetic: '/ˈsɜːvɪs/', meaning_zh: '服务', meaning_en: 'help provided to customers', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'set', phonetic: '/set/', meaning_zh: '放置；一套；设置', meaning_en: 'to put; a group of things', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'several', phonetic: '/ˈsevrəl/', meaning_zh: '几个', meaning_en: 'more than two but not many', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'share', phonetic: '/ʃeə(r)/', meaning_zh: '分享；股份', meaning_en: 'to give part to others', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'short', phonetic: '/ʃɔːt/', meaning_zh: '短的', meaning_en: 'not long', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'should', phonetic: '/ʃʊd/', meaning_zh: '应该', meaning_en: 'used to say what is right', pos: 'modal', difficulty: 1, theme: 'daily' },
  { word: 'show', phonetic: '/ʃəʊ/', meaning_zh: '展示；演出', meaning_en: 'to let someone see', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'side', phonetic: '/saɪd/', meaning_zh: '边；方面', meaning_en: 'a surface or edge', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'sign', phonetic: '/saɪn/', meaning_zh: '标志；签名', meaning_en: 'a symbol; to write your name', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'simple', phonetic: '/ˈsɪmpl/', meaning_zh: '简单的', meaning_en: 'easy to understand', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'since', phonetic: '/sɪns/', meaning_zh: '自从；因为', meaning_en: 'from a time in the past; because', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'single', phonetic: '/ˈsɪŋɡl/', meaning_zh: '单一的；单身的', meaning_en: 'only one; not married', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'sit', phonetic: '/sɪt/', meaning_zh: '坐', meaning_en: 'to rest on a chair', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'site', phonetic: '/saɪt/', meaning_zh: '地点；网站', meaning_en: 'a place; a website', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'situation', phonetic: '/ˌsɪtʃuˈeɪʃn/', meaning_zh: '情况', meaning_en: 'the way things are at a time', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'size', phonetic: '/saɪz/', meaning_zh: '尺寸', meaning_en: 'how big something is', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'skill', phonetic: '/skɪl/', meaning_zh: '技能', meaning_en: 'the ability to do something well', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'small', phonetic: '/smɔːl/', meaning_zh: '小的', meaning_en: 'not large', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'social', phonetic: '/ˈsəʊʃl/', meaning_zh: '社会的；社交的', meaning_en: 'relating to society or people', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'society', phonetic: '/səˈsaɪəti/', meaning_zh: '社会', meaning_en: 'people living together as a community', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'solve', phonetic: '/sɒlv/', meaning_zh: '解决', meaning_en: 'to find an answer to a problem', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'someone', phonetic: '/ˈsʌmwʌn/', meaning_zh: '某人', meaning_en: 'an unknown person', pos: 'pron', difficulty: 1, theme: 'daily' },
  { word: 'something', phonetic: '/ˈsʌmθɪŋ/', meaning_zh: '某事；某物', meaning_en: 'an unknown thing', pos: 'pron', difficulty: 1, theme: 'daily' },
  { word: 'sometimes', phonetic: '/ˈsʌmtaɪmz/', meaning_zh: '有时', meaning_en: 'on some occasions', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'sound', phonetic: '/saʊnd/', meaning_zh: '声音；听起来', meaning_en: 'what you hear', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'source', phonetic: '/sɔːs/', meaning_zh: '来源', meaning_en: 'where something comes from', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'space', phonetic: '/speɪs/', meaning_zh: '空间；太空', meaning_en: 'room; the area beyond Earth', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'speak', phonetic: '/spiːk/', meaning_zh: '说话', meaning_en: 'to say words', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'special', phonetic: '/ˈspeʃl/', meaning_zh: '特别的', meaning_en: 'not ordinary', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'specific', phonetic: '/spəˈsɪfɪk/', meaning_zh: '具体的', meaning_en: 'clearly defined; particular', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'spend', phonetic: '/spend/', meaning_zh: '花费；度过', meaning_en: 'to use money or time', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'sport', phonetic: '/spɔːt/', meaning_zh: '运动', meaning_en: 'physical games and activities', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'staff', phonetic: '/stɑːf/', meaning_zh: '员工', meaning_en: 'the people who work for an organization', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'stage', phonetic: '/steɪdʒ/', meaning_zh: '阶段；舞台', meaning_en: 'a step in a process; a platform', pos: 'n', difficulty: 2, theme: 'game' },
  { word: 'stand', phonetic: '/stænd/', meaning_zh: '站立；忍受', meaning_en: 'to be on your feet', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'standard', phonetic: '/ˈstændəd/', meaning_zh: '标准', meaning_en: 'a level used for measuring quality', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'start', phonetic: '/stɑːt/', meaning_zh: '开始', meaning_en: 'to begin', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'state', phonetic: '/steɪt/', meaning_zh: '状态；州；陈述', meaning_en: 'condition; a region; to say', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'statement', phonetic: '/ˈsteɪtmənt/', meaning_zh: '声明；陈述', meaning_en: 'something said or written', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'stay', phonetic: '/steɪ/', meaning_zh: '停留；保持', meaning_en: 'to remain in a place', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'step', phonetic: '/step/', meaning_zh: '步骤；脚步', meaning_en: 'a stage in a process; a foot movement', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'still', phonetic: '/stɪl/', meaning_zh: '仍然；静止的', meaning_en: 'continuing; not moving', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'stop', phonetic: '/stɒp/', meaning_zh: '停止', meaning_en: 'to end an action', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'store', phonetic: '/stɔː(r)/', meaning_zh: '商店；储存', meaning_en: 'a shop; to keep for later', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'story', phonetic: '/ˈstɔːri/', meaning_zh: '故事', meaning_en: 'an account of events', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'street', phonetic: '/striːt/', meaning_zh: '街道', meaning_en: 'a public road in a city', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'strong', phonetic: '/strɒŋ/', meaning_zh: '强壮的；强烈的', meaning_en: 'having power', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'structure', phonetic: '/ˈstrʌktʃə(r)/', meaning_zh: '结构', meaning_en: 'the way parts are arranged', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'student', phonetic: '/ˈstjuːdnt/', meaning_zh: '学生', meaning_en: 'a person who is studying', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'study', phonetic: '/ˈstʌdi/', meaning_zh: '学习；研究', meaning_en: 'to learn about a subject', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'style', phonetic: '/staɪl/', meaning_zh: '风格', meaning_en: 'a way of doing or designing', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'subject', phonetic: '/ˈsʌbdʒɪkt/', meaning_zh: '主题；科目', meaning_en: 'a topic of study', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'success', phonetic: '/səkˈses/', meaning_zh: '成功', meaning_en: 'achieving what you wanted', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'such', phonetic: '/sʌtʃ/', meaning_zh: '这样的', meaning_en: 'of that kind', pos: 'det', difficulty: 1, theme: 'daily' },
  { word: 'suggest', phonetic: '/səˈdʒest/', meaning_zh: '建议；暗示', meaning_en: 'to propose an idea', pos: 'v', difficulty: 2, theme: 'study' },
  { word: 'support', phonetic: '/səˈpɔːt/', meaning_zh: '支持', meaning_en: 'to help or agree with', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'sure', phonetic: '/ʃʊə(r)/', meaning_zh: '确定的', meaning_en: 'confident that something is true', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'system', phonetic: '/ˈsɪstəm/', meaning_zh: '系统', meaning_en: 'a set of connected parts', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'table', phonetic: '/ˈteɪbl/', meaning_zh: '桌子；表格', meaning_en: 'furniture; a chart of data', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'take', phonetic: '/teɪk/', meaning_zh: '拿；花费', meaning_en: 'to get hold of; to require time', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'talk', phonetic: '/tɔːk/', meaning_zh: '谈话', meaning_en: 'to speak with someone', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'task', phonetic: '/tɑːsk/', meaning_zh: '任务', meaning_en: 'a piece of work to be done', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'teach', phonetic: '/tiːtʃ/', meaning_zh: '教', meaning_en: 'to help someone learn', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'team', phonetic: '/tiːm/', meaning_zh: '团队', meaning_en: 'a group working together', pos: 'n', difficulty: 1, theme: 'game' },
  { word: 'technology', phonetic: '/tekˈnɒlədʒi/', meaning_zh: '技术', meaning_en: 'scientific knowledge used in practice', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'tell', phonetic: '/tel/', meaning_zh: '告诉', meaning_en: 'to give information in words', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'term', phonetic: '/tɜːm/', meaning_zh: '学期；术语', meaning_en: 'a period of study; a word', pos: 'n', difficulty: 2, theme: 'study' },
  { word: 'test', phonetic: '/test/', meaning_zh: '测试', meaning_en: 'an exam; to check', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'than', phonetic: '/ðæn/', meaning_zh: '比', meaning_en: 'used in comparisons', pos: 'conj', difficulty: 1, theme: 'daily' },
  { word: 'thank', phonetic: '/θæŋk/', meaning_zh: '感谢', meaning_en: 'to express gratitude', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'theory', phonetic: '/ˈθɪəri/', meaning_zh: '理论', meaning_en: 'an idea that explains something', pos: 'n', difficulty: 3, theme: 'study' },
  { word: 'thing', phonetic: '/θɪŋ/', meaning_zh: '东西；事情', meaning_en: 'an object or matter', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'think', phonetic: '/θɪŋk/', meaning_zh: '思考；认为', meaning_en: 'to use the mind; to believe', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'though', phonetic: '/ðəʊ/', meaning_zh: '虽然', meaning_en: 'despite the fact that', pos: 'conj', difficulty: 2, theme: 'study' },
  { word: 'thought', phonetic: '/θɔːt/', meaning_zh: '想法；思考', meaning_en: 'an idea; the process of thinking', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'three', phonetic: '/θriː/', meaning_zh: '三', meaning_en: 'the number 3', pos: 'num', difficulty: 1, theme: 'daily' },
  { word: 'through', phonetic: '/θruː/', meaning_zh: '穿过；通过', meaning_en: 'from one end to the other', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'time', phonetic: '/taɪm/', meaning_zh: '时间', meaning_en: 'minutes, hours, days etc.', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'today', phonetic: '/təˈdeɪ/', meaning_zh: '今天', meaning_en: 'this day', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'together', phonetic: '/təˈɡeðə(r)/', meaning_zh: '一起', meaning_en: 'with each other', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'tomorrow', phonetic: '/təˈmɒrəʊ/', meaning_zh: '明天', meaning_en: 'the day after today', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'tonight', phonetic: '/təˈnaɪt/', meaning_zh: '今晚', meaning_en: 'this evening or night', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'total', phonetic: '/ˈtəʊtl/', meaning_zh: '总计；完全的', meaning_en: 'complete amount; entire', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'toward', phonetic: '/təˈwɔːd/', meaning_zh: '朝向', meaning_en: 'in the direction of', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'trade', phonetic: '/treɪd/', meaning_zh: '贸易；交易', meaning_en: 'buying and selling', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'train', phonetic: '/treɪn/', meaning_zh: '火车；训练', meaning_en: 'a railway vehicle; to practice', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'travel', phonetic: '/ˈtrævl/', meaning_zh: '旅行', meaning_en: 'to go from place to place', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'treat', phonetic: '/triːt/', meaning_zh: '对待；治疗', meaning_en: 'to behave toward; to give medical care', pos: 'v', difficulty: 2, theme: 'daily' },
  { word: 'tree', phonetic: '/triː/', meaning_zh: '树', meaning_en: 'a tall plant with a trunk', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'true', phonetic: '/truː/', meaning_zh: '真实的', meaning_en: 'correct; not false', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'try', phonetic: '/traɪ/', meaning_zh: '尝试', meaning_en: 'to make an effort', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'turn', phonetic: '/tɜːn/', meaning_zh: '转动；轮到', meaning_en: 'to change direction; a chance', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'type', phonetic: '/taɪp/', meaning_zh: '类型；打字', meaning_en: 'a kind; to write with a keyboard', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'under', phonetic: '/ˈʌndə(r)/', meaning_zh: '在…下面', meaning_en: 'below', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'understand', phonetic: '/ˌʌndəˈstænd/', meaning_zh: '理解', meaning_en: 'to know the meaning of', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'unit', phonetic: '/ˈjuːnɪt/', meaning_zh: '单元；单位', meaning_en: 'a single part of a whole', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'until', phonetic: '/ənˈtɪl/', meaning_zh: '直到', meaning_en: 'up to the time of', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'upon', phonetic: '/əˈpɒn/', meaning_zh: '在…之上', meaning_en: 'on (formal)', pos: 'prep', difficulty: 2, theme: 'study' },
  { word: 'use', phonetic: '/juːz/', meaning_zh: '使用', meaning_en: 'to do something with', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'usual', phonetic: '/ˈjuːʒuəl/', meaning_zh: '通常的', meaning_en: 'normal; common', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'value', phonetic: '/ˈvæljuː/', meaning_zh: '价值', meaning_en: 'how useful or important something is', pos: 'n', difficulty: 2, theme: 'work' },
  { word: 'various', phonetic: '/ˈveəriəs/', meaning_zh: '各种各样的', meaning_en: 'of different kinds', pos: 'adj', difficulty: 2, theme: 'study' },
  { word: 'very', phonetic: '/ˈveri/', meaning_zh: '非常', meaning_en: 'to a high degree', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'view', phonetic: '/vjuː/', meaning_zh: '观点；景色', meaning_en: 'an opinion; what you can see', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'visit', phonetic: '/ˈvɪzɪt/', meaning_zh: '拜访；参观', meaning_en: 'to go to see a place or person', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'voice', phonetic: '/vɔɪs/', meaning_zh: '声音；嗓音', meaning_en: 'the sound from the mouth when speaking', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'wait', phonetic: '/weɪt/', meaning_zh: '等待', meaning_en: 'to stay until something happens', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'walk', phonetic: '/wɔːk/', meaning_zh: '走；散步', meaning_en: 'to move on foot', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'want', phonetic: '/wɒnt/', meaning_zh: '想要', meaning_en: 'to wish for', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'watch', phonetic: '/wɒtʃ/', meaning_zh: '观看；手表', meaning_en: 'to look at; a timepiece', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'water', phonetic: '/ˈwɔːtə(r)/', meaning_zh: '水', meaning_en: 'the clear liquid we drink', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'way', phonetic: '/weɪ/', meaning_zh: '方式；路', meaning_en: 'a method; a path', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'week', phonetic: '/wiːk/', meaning_zh: '星期', meaning_en: 'seven days', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'well', phonetic: '/wel/', meaning_zh: '好地；健康的', meaning_en: 'in a good way; healthy', pos: 'adv', difficulty: 1, theme: 'daily' },
  { word: 'whether', phonetic: '/ˈweðə(r)/', meaning_zh: '是否', meaning_en: 'if … or not', pos: 'conj', difficulty: 2, theme: 'study' },
  { word: 'while', phonetic: '/waɪl/', meaning_zh: '当…时；而', meaning_en: 'during the time that', pos: 'conj', difficulty: 1, theme: 'daily' },
  { word: 'white', phonetic: '/waɪt/', meaning_zh: '白色的', meaning_en: 'the color of snow', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'whole', phonetic: '/həʊl/', meaning_zh: '整个的', meaning_en: 'complete; all of', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'whose', phonetic: '/huːz/', meaning_zh: '谁的', meaning_en: 'belonging to which person', pos: 'pron', difficulty: 1, theme: 'daily' },
  { word: 'wide', phonetic: '/waɪd/', meaning_zh: '宽的', meaning_en: 'measuring a large distance from side to side', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'wife', phonetic: '/waɪf/', meaning_zh: '妻子', meaning_en: 'a married woman in relation to her husband', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'will', phonetic: '/wɪl/', meaning_zh: '将；意愿', meaning_en: 'used for future; desire', pos: 'modal', difficulty: 1, theme: 'daily' },
  { word: 'win', phonetic: '/wɪn/', meaning_zh: '赢', meaning_en: 'to be the best in a contest', pos: 'v', difficulty: 1, theme: 'game' },
  { word: 'window', phonetic: '/ˈwɪndəʊ/', meaning_zh: '窗户', meaning_en: 'an opening in a wall with glass', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'wish', phonetic: '/wɪʃ/', meaning_zh: '希望；愿望', meaning_en: 'to want something to happen', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'within', phonetic: '/wɪˈðɪn/', meaning_zh: '在…之内', meaning_en: 'inside the limits of', pos: 'prep', difficulty: 2, theme: 'study' },
  { word: 'without', phonetic: '/wɪˈðaʊt/', meaning_zh: '没有', meaning_en: 'not having', pos: 'prep', difficulty: 1, theme: 'daily' },
  { word: 'woman', phonetic: '/ˈwʊmən/', meaning_zh: '女人', meaning_en: 'an adult female person', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'wonder', phonetic: '/ˈwʌndə(r)/', meaning_zh: '想知道；奇迹', meaning_en: 'to feel curious; amazing thing', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'word', phonetic: '/wɜːd/', meaning_zh: '单词；话语', meaning_en: 'a unit of language', pos: 'n', difficulty: 1, theme: 'study' },
  { word: 'work', phonetic: '/wɜːk/', meaning_zh: '工作', meaning_en: 'activity to earn money or achieve', pos: 'n', difficulty: 1, theme: 'work' },
  { word: 'world', phonetic: '/wɜːld/', meaning_zh: '世界', meaning_en: 'the earth and all people', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'worry', phonetic: '/ˈwʌri/', meaning_zh: '担心', meaning_en: 'to feel anxious', pos: 'v', difficulty: 1, theme: 'daily' },
  { word: 'write', phonetic: '/raɪt/', meaning_zh: '写', meaning_en: 'to form letters or words', pos: 'v', difficulty: 1, theme: 'study' },
  { word: 'wrong', phonetic: '/rɒŋ/', meaning_zh: '错误的', meaning_en: 'not correct', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'year', phonetic: '/jɪə(r)/', meaning_zh: '年', meaning_en: 'twelve months', pos: 'n', difficulty: 1, theme: 'daily' },
  { word: 'young', phonetic: '/jʌŋ/', meaning_zh: '年轻的', meaning_en: 'not old', pos: 'adj', difficulty: 1, theme: 'daily' },
  { word: 'yourself', phonetic: '/jɔːˈself/', meaning_zh: '你自己', meaning_en: 'the person you are speaking to', pos: 'pron', difficulty: 1, theme: 'daily' },
];
